"""Cloudflare R2 access (S3-compatible). The bucket is private — there is
no public-URL path here. All read access to an object goes through a
short-lived presigned GET URL generated by `generate_signed_url`."""

import boto3

from config import Config


def get_spaces_client():
    return boto3.client(
        "s3",
        region_name="auto",
        endpoint_url=f"https://{Config.CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com",
        aws_access_key_id=Config.R2_ACCESS_KEY_ID,
        aws_secret_access_key=Config.R2_SECRET_ACCESS_KEY,
    )


def generate_signed_url(key: str, expires_in: int = 300) -> str:
    """
    Generate a temporary private R2 URL for reading an object.

    The URL expires automatically after `expires_in` seconds.
    """
    client = get_spaces_client()

    return client.generate_presigned_url(
        "get_object",
        Params={
            "Bucket": Config.R2_BUCKET_NAME,
            "Key": key,
        },
        ExpiresIn=expires_in,
    )


def delete_object(key: str) -> None:
    """Delete a single object from R2. Silently ignores failures (e.g.
    NoSuchKey) — deleting a file that's already gone isn't an error for
    any of this module's callers."""
    client = get_spaces_client()
    try:
        client.delete_object(Bucket=Config.R2_BUCKET_NAME, Key=key)
    except Exception:
        pass
