"""add upload files

Revision ID: 1d696b7bf091
Revises: 
Create Date: 2026-08-26 22:20:09.863013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d696b7bf091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_upload_file_user_id','user',['user_id'],['id'])
        batch_op.drop_column('origianl_filename')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bank_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origianl_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_upload_file_user_id',type_='foreignkey')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
