"""add profile fields, preferences, goals, transactions, activity, notifications, document metadata

Revision ID: 29bd12a2dde1
Revises: 7f3a92c1d4e5
Create Date: 2026-09-06 18:40:34.912022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bd12a2dde1'
down_revision = '7f3a92c1d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('activity_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_user_id'), ['user_id'], unique=False)

    op.create_table('financial_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_goal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_goal_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('notification_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('financial_reminders', sa.Boolean(), nullable=False),
    sa.Column('goal_notifications', sa.Boolean(), nullable=False),
    sa.Column('document_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preference_user_id'), ['user_id'], unique=True)

    # `server_default` on the new NOT NULL columns backfills the rows that
    # already exist in this table; it matches each column's Python-side
    # default in models.py so newly inserted rows behave the same either way.
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=30), nullable=False, server_default='other'))
        batch_op.add_column(sa.Column('financial_period_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('financial_period_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.String(length=20), nullable=False, server_default='uploaded'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='NGN'))
        batch_op.add_column(sa.Column('occupation', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('income', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('income_frequency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('income_frequency')
        batch_op.drop_column('income')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('occupation')
        batch_op.drop_column('currency')
        batch_op.drop_column('country')

    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.drop_column('processing_status')
        batch_op.drop_column('financial_period_end')
        batch_op.drop_column('financial_period_start')
        batch_op.drop_column('document_type')

    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preference_user_id'))

    op.drop_table('user_preference')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))

    op.drop_table('transaction')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_goal_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_goal_status'))

    op.drop_table('financial_goal')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_created_at'))

    op.drop_table('activity')
    # ### end Alembic commands ###
